package com.qiuhn.gudu.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.qiuhn.gudu.dao.SchoolDao;
import com.qiuhn.gudu.dao.DepartmentDao;
import com.qiuhn.gudu.dao.SchoolAliasDao;
import com.qiuhn.gudu.dao.ForumTopicDao;
import com.qiuhn.gudu.dao.ForumReplyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SchoolDao.createTable(db, ifNotExists);
        DepartmentDao.createTable(db, ifNotExists);
        SchoolAliasDao.createTable(db, ifNotExists);
        ForumTopicDao.createTable(db, ifNotExists);
        ForumReplyDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SchoolDao.dropTable(db, ifExists);
        DepartmentDao.dropTable(db, ifExists);
        SchoolAliasDao.dropTable(db, ifExists);
        ForumTopicDao.dropTable(db, ifExists);
        ForumReplyDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SchoolDao.class);
        registerDaoClass(DepartmentDao.class);
        registerDaoClass(SchoolAliasDao.class);
        registerDaoClass(ForumTopicDao.class);
        registerDaoClass(ForumReplyDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
