package com.qiuhn.gudu.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.qiuhn.gudu.domain.SchoolAlias;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table t_school_alias.
*/
public class SchoolAliasDao extends AbstractDao<SchoolAlias, Integer> {

    public static final String TABLENAME = "t_school_alias";

    /**
     * Properties of entity SchoolAlias.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "id", true, "_id");
        public final static Property School_id = new Property(1, int.class, "school_id", false, "SCHOOL_ID");
        public final static Property Master_name = new Property(2, String.class, "master_name", false, "MASTER_NAME");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Pinyin = new Property(4, String.class, "pinyin", false, "PINYIN");
        public final static Property Py = new Property(5, String.class, "py", false, "PY");
    };


    public SchoolAliasDao(DaoConfig config) {
        super(config);
    }
    
    public SchoolAliasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'t_school_alias' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SCHOOL_ID' INTEGER NOT NULL ," + // 1: school_id
                "'MASTER_NAME' TEXT," + // 2: master_name
                "'NAME' TEXT," + // 3: name
                "'PINYIN' TEXT," + // 4: pinyin
                "'PY' TEXT);"); // 5: py
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'t_school_alias'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SchoolAlias entity) {
        stmt.clearBindings();
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSchool_id());
 
        String master_name = entity.getMaster_name();
        if (master_name != null) {
            stmt.bindString(3, master_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(5, pinyin);
        }
 
        String py = entity.getPy();
        if (py != null) {
            stmt.bindString(6, py);
        }
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SchoolAlias readEntity(Cursor cursor, int offset) {
        SchoolAlias entity = new SchoolAlias( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // id
            cursor.getInt(offset + 1), // school_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // master_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pinyin
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // py
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SchoolAlias entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setSchool_id(cursor.getInt(offset + 1));
        entity.setMaster_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPinyin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPy(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(SchoolAlias entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(SchoolAlias entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
