package com.qiuhn.gudu.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table t_forum_reply.
 */
public class ForumReply {

    private String id;
    private String content;
    private String imgs;
    private Long userId;
    private Long createDate;
    private Long index;
    private Byte status;

    public ForumReply() {
    }

    public ForumReply(String id) {
        this.id = id;
    }

    public ForumReply(String id, String content, String imgs, Long userId, Long createDate, Long index, Byte status) {
        this.id = id;
        this.content = content;
        this.imgs = imgs;
        this.userId = userId;
        this.createDate = createDate;
        this.index = index;
        this.status = status;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImgs() {
        return imgs;
    }

    public void setImgs(String imgs) {
        this.imgs = imgs;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public Long getIndex() {
        return index;
    }

    public void setIndex(Long index) {
        this.index = index;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

}
