package com.qiuhn.gudu.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table t_forum_topic.
 */
public class ForumTopic {

    private String id;
    private String title;
    private String content;
    private String imgs;
    private Integer schoolId;
    private Integer likeCount;
    private Integer replyCount;
    private Long userId;
    private Long createDate;
    private Long latestUpdateTime;
    private Byte status;
    private Byte meLike;

    public ForumTopic() {
    }

    public ForumTopic(String id) {
        this.id = id;
    }

    public ForumTopic(String id, String title, String content, String imgs, Integer schoolId, Integer likeCount, Integer replyCount, Long userId, Long createDate, Long latestUpdateTime, Byte status, Byte meLike) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.imgs = imgs;
        this.schoolId = schoolId;
        this.likeCount = likeCount;
        this.replyCount = replyCount;
        this.userId = userId;
        this.createDate = createDate;
        this.latestUpdateTime = latestUpdateTime;
        this.status = status;
        this.meLike = meLike;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImgs() {
        return imgs;
    }

    public void setImgs(String imgs) {
        this.imgs = imgs;
    }

    public Integer getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    public Integer getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    public Integer getReplyCount() {
        return replyCount;
    }

    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    public Long getLatestUpdateTime() {
        return latestUpdateTime;
    }

    public void setLatestUpdateTime(Long latestUpdateTime) {
        this.latestUpdateTime = latestUpdateTime;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getMeLike() {
        return meLike;
    }

    public void setMeLike(Byte meLike) {
        this.meLike = meLike;
    }

}
